name: Build and Push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  maven-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Debug extracted version
        run: |
          echo "Extracted version: ${{ env.VERSION }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: |
          REPO_NAME=${{ github.repository }}
          IMAGE_NAME=${REPO_NAME#*/}
          docker build --build-arg GITHUB_TOKEN=${{ secrets.GH_TOKEN }} -t ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ github.repository_owner }}/$IMAGE_NAME:${{ env.VERSION }}
          docker push ghcr.io/${IMAGE_NAME}