name: Build and Push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  maven-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          cd code
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Convert repository owner and repo name to lowercase
        id: lowercase
        run: |
          # Extrae el propietario y el nombre del repositorio y conviértelos a minúsculas
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.repository }}
          IMAGE_NAME=${REPO_NAME#*/}
          REPO_OWNER_LOWER=$(echo "$REPO_OWNER" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER_LOWER=${REPO_OWNER_LOWER}" >> $GITHUB_ENV
          echo "IMAGE_NAME_LOWER=${IMAGE_NAME_LOWER}" >> $GITHUB_ENV

      - name: Debug extracted version, owner, and image name
        run: |
          echo "Extracted version: ${{ env.VERSION }}"
          echo "Repository owner (lowercase): ${{ env.REPO_OWNER_LOWER }}"
          echo "Image name (lowercase): ${{ env.IMAGE_NAME_LOWER }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --build-arg GITHUB_TOKEN=${{ secrets.GH_TOKEN }} -t ghcr.io/${{ env.REPO_OWNER_LOWER }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER_LOWER }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.VERSION }}